server:
  port: 0
spring:
  application:
    name: codegen-cloudconsumer
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    name: cloud_meeting
    url: jdbc:mysql://local:3306/information_schema?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: local
    password: local
#配置mybatis
mybatisPlus:
  #打印日志
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
buildconfig:
  packageName: com.bosscloud.demoopenapiwebflux
  artifactName: BosscloudWebfluxDemoOpenApi
  artifactId: bosscloud-demoopenapiwebflux
  springBootVersion: 2.3.0.RELEASE
  springCloudVersion: Hoxton.SR4
  projectVersion: 1.0.0
  saveDir: /Users/huangqijun/homefolder/project/tojoy/bosscloud/bosscloud-example-webflux/bosscloud-demoopenapiwebflux
  tableSchema: boss_cloud_demo
