server:
  port: 0
spring:
  application:
    name: codegen-cloudprovider
  redis:
    host: localhost
    password:
    port: 6379
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    name: bosscloud_app
    url: jdbc:mysql://dev-new-tojoyboss.mysql.rds.aliyuncs.com:3306/information_schema?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: dev_tojoy_cloud
    password: Q4uGvQeNo3O7AIYd
#配置mybatis
mybatisPlus:
  #打印日志
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
buildconfig:
  packageName: com.study.build.cloudprovider
  artifactName: CodegenProvider
  artifactId: codegen-provider
  springBootVersion: 2.3.5.RELEASE
  springCloudVersion: Hoxton.SR9
  projectVersion: 1.0.0
  saveDir: /Users/huangqijun/tem/cloudprovider
  tableSchema: bosscloud_sundries_platform