server:
  port: 0
spring:
  application:
    name: cust-track
  redis:
    host: localhost
    password:
    port: 6379
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    name: bosscloud_app
    url: jdbc:mysql://82.157.45.178:3306/information_schema?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Admin_talent
#配置mybatis
mybatisPlus:
  #打印日志
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
buildconfig:
  packageName: com.talent
  artifactName: talent-user
  artifactId: talent-user
  springBootVersion: 2.5.4
  springCloudVersion: 2020.0.3
  projectVersion: 1.0.0
  saveDir: /Users/huangqijun/tem/talent-user
  tableSchema: talent_user
