server:
  port: 0
spring:
  application:
    name: codegen-cloudprovider
  redis:
    host: 127.0.0.1
    password:
    port: 6379
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    name: cloud_meeting
    url: jdbc:mysql://localhost:3306/information_schema?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
#配置mybatis
mybatisPlus:
  #打印日志
  configuration:
     logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
buildconfig:
  packageName: com.study.build.cloudprovider
  artifactName: CodegenCloudProvider
  artifactId: codegen-build-cloudprovider
  springBootVersion: 2.2.5.RELEASE
  springCloudVersion: Hoxton.SR3
  projectVersion: 1.0.0
  saveDir: /Users/huangqijun/tem
  tableSchema: codegen_build